# URLControl Settings Configuration
targets:
  domains: []
  default_paths:
    - "/admin"
    - "/api" 
    - "/backup"
    - "/config"
    - "/dashboard"
    - "/login"
    - "/panel"
    - "/phpmyadmin"
    - "/wp-admin"

payloads:
  directories:
    - "admin"
    - "api"
    - "backup"
    - "config"
    - "dashboard"
    - "login"
    - "panel"
    - "test"
    - "dev"
    - "staging"
  files:
    - "config.php"
    - "admin.php" 
    - "login.php"
    - "test.php"
    - "backup.sql"
    - "database.sql"
    - ".env"
    - "config.json"

scan_settings:
  max_depth: 3
  follow_redirects: true
  verify_ssl: false
  custom_headers: {}
